// ============================================================
// SkyVest — Mock Data Repository
// ============================================================

import type {
  Company,
  Holding,
  Enquiry,
  WatchlistItem,
  Portfolio,
  PortfolioPerformancePoint,
  AllocationItem,
  KYC,
  Profile,
} from "@/lib/types"

// ─── Companies ───────────────────────────────────────────────

export const companies: Company[] = [
  {
    id: "nse-india",
    name: "NSE India",
    slug: "nse-india",
    sector: "Financial Infrastructure",
    category: "Exchange & Infrastructure",
    status: "unlisted",
    indicativePrice: 1998,
    previousPrice: 1920,
    priceChange: 78,
    priceChangePercent: 4.06,
    lastUpdated: "2026-08-19",
    description:
      "National Stock Exchange of India is the leading stock exchange in India and the fourth largest in the world by equity trading volume. It was established in 1992 as a demutualised digital exchange and has been a cornerstone of India's capital markets.",
    founded: "1992",
    headquarters: "Mumbai, Maharashtra",
    employees: "4,000+",
    revenue: "₹14,778 Cr (FY24)",
    valuation: "₹2.1 Lakh Cr (indicative)",
    promoters: "Institutional (LIC, SBI, IDFC, IL&FS)",
    logoInitials: "NSE",
    logoColor: "#0EA5E9",
  },
  {
    id: "hdfc-securities",
    name: "HDFC Securities",
    slug: "hdfc-securities",
    sector: "Financial Services",
    category: "Broking & Wealth",
    status: "pre-ipo",
    indicativePrice: 3450,
    previousPrice: 3380,
    priceChange: 70,
    priceChangePercent: 2.07,
    lastUpdated: "2026-08-19",
    description:
      "HDFC Securities is a premier full-service broking house with a comprehensive suite of investment products, from equities and derivatives to mutual funds and bonds. It is a subsidiary of HDFC Bank.",
    founded: "2000",
    headquarters: "Mumbai, Maharashtra",
    employees: "2,800+",
    revenue: "₹2,400 Cr (FY24)",
    valuation: "₹18,000 Cr (indicative)",
    promoters: "HDFC Bank Ltd",
    logoInitials: "HDFC",
    logoColor: "#16A37A",
  },
  {
    id: "tata-capital",
    name: "Tata Capital",
    slug: "tata-capital",
    sector: "Financial Services",
    category: "NBFC & Lending",
    status: "pre-ipo",
    indicativePrice: 950,
    previousPrice: 910,
    priceChange: 40,
    priceChangePercent: 4.4,
    lastUpdated: "2026-08-19",
    description:
      "Tata Capital is the financial services arm of the Tata Group, offering a comprehensive range of financial services for commercial, corporate and retail customers as well as high networth individuals.",
    founded: "2007",
    headquarters: "Mumbai, Maharashtra",
    employees: "12,000+",
    revenue: "₹16,340 Cr (FY24)",
    valuation: "₹80,000 Cr (indicative)",
    promoters: "Tata Sons Pvt Ltd",
    logoInitials: "TC",
    logoColor: "#6366f1",
  },
  {
    id: "oyo",
    name: "OYO Rooms",
    slug: "oyo",
    sector: "Consumer Technology",
    category: "Hospitality Tech",
    status: "pre-ipo",
    indicativePrice: 38,
    previousPrice: 42,
    priceChange: -4,
    priceChangePercent: -9.52,
    lastUpdated: "2026-08-19",
    description:
      "OYO Hotels & Homes is a global travel technology company that provides travellers with a wide range of hotels, homes, and spaces. Present in 35+ countries with a technology-first approach to hospitality.",
    founded: "2013",
    headquarters: "Gurugram, Haryana",
    employees: "3,500+",
    revenue: "₹5,464 Cr (FY24)",
    valuation: "₹18,000 Cr (indicative)",
    promoters: "Ritesh Agarwal, Softbank Vision Fund",
    logoInitials: "OYO",
    logoColor: "#D99A24",
  },
  {
    id: "swiggy",
    name: "Swiggy",
    slug: "swiggy",
    sector: "Consumer Technology",
    category: "Food & Quick Commerce",
    status: "unlisted",
    indicativePrice: 395,
    previousPrice: 375,
    priceChange: 20,
    priceChangePercent: 5.33,
    lastUpdated: "2026-08-19",
    description:
      "Swiggy is India's leading online food ordering and delivery platform, now expanding aggressively into quick commerce (Instamart) and dining-out. It competes directly with Zomato across all verticals.",
    founded: "2014",
    headquarters: "Bengaluru, Karnataka",
    employees: "5,000+",
    revenue: "₹11,247 Cr (FY24)",
    valuation: "₹87,000 Cr (indicative)",
    promoters: "Sriharsha Majety, Prosus, Accel",
    logoInitials: "SWG",
    logoColor: "#f97316",
  },
  {
    id: "hexaware",
    name: "Hexaware Technologies",
    slug: "hexaware",
    sector: "Technology",
    category: "IT Services",
    status: "pre-ipo",
    indicativePrice: 755,
    previousPrice: 740,
    priceChange: 15,
    priceChangePercent: 2.03,
    lastUpdated: "2026-08-19",
    description:
      "Hexaware Technologies is a global IT and BPO services company headquartered in Mumbai. It offers digital transformation, AI/ML, cloud, and enterprise solutions to Fortune 500 companies worldwide.",
    founded: "1990",
    headquarters: "Navi Mumbai, Maharashtra",
    employees: "32,000+",
    revenue: "₹10,432 Cr (FY24)",
    valuation: "₹45,000 Cr (indicative)",
    promoters: "Carlyle Group",
    logoInitials: "HEX",
    logoColor: "#8b5cf6",
  },
  {
    id: "msei",
    name: "MSEI",
    slug: "msei",
    sector: "Financial Infrastructure",
    category: "Exchange & Infrastructure",
    status: "unlisted",
    indicativePrice: 3.4,
    previousPrice: 3.2,
    priceChange: 0.2,
    priceChangePercent: 6.25,
    lastUpdated: "2026-08-19",
    description:
      "Metropolitan Stock Exchange of India (MSEI) is a recognised stock exchange providing a trading platform for equities, derivatives, and currency products with a technology-first approach.",
    founded: "2008",
    headquarters: "Mumbai, Maharashtra",
    employees: "300+",
    revenue: "₹48 Cr (FY24)",
    valuation: "₹220 Cr (indicative)",
    promoters: "Institutional Investors",
    logoInitials: "MSE",
    logoColor: "#22D3EE",
  },
  {
    id: "waaree-energies",
    name: "Waaree Energies",
    slug: "waaree-energies",
    sector: "Renewable Energy",
    category: "Solar Manufacturing",
    status: "pre-ipo",
    indicativePrice: 1850,
    previousPrice: 1780,
    priceChange: 70,
    priceChangePercent: 3.93,
    lastUpdated: "2026-08-19",
    description:
      "Waaree Energies is India's largest solar panel manufacturer with an installed capacity of 12 GW. It is at the forefront of India's energy transition with a strong export presence across 68+ countries.",
    founded: "1990",
    headquarters: "Mumbai, Maharashtra",
    employees: "4,500+",
    revenue: "₹11,642 Cr (FY24)",
    valuation: "₹53,000 Cr (indicative)",
    promoters: "Hitesh Chimanlal Doshi",
    logoInitials: "WE",
    logoColor: "#16A37A",
  },
]

// ─── Holdings ────────────────────────────────────────────────

export const holdings: Holding[] = [
  {
    id: "h1",
    companyId: "nse-india",
    companyName: "NSE India",
    companySector: "Financial Infrastructure",
    companyCategory: "Exchange & Infrastructure",
    companyStatus: "unlisted",
    quantity: 100,
    averageCost: 1650,
    indicativePrice: 1998,
    currentValue: 199800,
    investedValue: 165000,
    gain: 34800,
    gainPercent: 21.09,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h2",
    companyId: "hdfc-securities",
    companyName: "HDFC Securities",
    companySector: "Financial Services",
    companyCategory: "Broking & Wealth",
    companyStatus: "pre-ipo",
    quantity: 50,
    averageCost: 2900,
    indicativePrice: 3450,
    currentValue: 172500,
    investedValue: 145000,
    gain: 27500,
    gainPercent: 18.97,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h3",
    companyId: "tata-capital",
    companyName: "Tata Capital",
    companySector: "Financial Services",
    companyCategory: "NBFC & Lending",
    companyStatus: "pre-ipo",
    quantity: 250,
    averageCost: 820,
    indicativePrice: 950,
    currentValue: 237500,
    investedValue: 205000,
    gain: 32500,
    gainPercent: 15.85,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h4",
    companyId: "oyo",
    companyName: "OYO Rooms",
    companySector: "Consumer Technology",
    companyCategory: "Hospitality Tech",
    companyStatus: "pre-ipo",
    quantity: 5000,
    averageCost: 45,
    indicativePrice: 38,
    currentValue: 190000,
    investedValue: 225000,
    gain: -35000,
    gainPercent: -15.56,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h5",
    companyId: "swiggy",
    companyName: "Swiggy",
    companySector: "Consumer Technology",
    companyCategory: "Food & Quick Commerce",
    companyStatus: "unlisted",
    quantity: 500,
    averageCost: 310,
    indicativePrice: 395,
    currentValue: 197500,
    investedValue: 155000,
    gain: 42500,
    gainPercent: 27.42,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h6",
    companyId: "hexaware",
    companyName: "Hexaware Technologies",
    companySector: "Technology",
    companyCategory: "IT Services",
    companyStatus: "pre-ipo",
    quantity: 300,
    averageCost: 640,
    indicativePrice: 755,
    currentValue: 226500,
    investedValue: 192000,
    gain: 34500,
    gainPercent: 17.97,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h7",
    companyId: "msei",
    companyName: "MSEI",
    companySector: "Financial Infrastructure",
    companyCategory: "Exchange & Infrastructure",
    companyStatus: "unlisted",
    quantity: 100000,
    averageCost: 3.0,
    indicativePrice: 3.4,
    currentValue: 340000,
    investedValue: 300000,
    gain: 40000,
    gainPercent: 13.33,
    lastUpdated: "2026-08-19",
  },
  {
    id: "h8",
    companyId: "waaree-energies",
    companyName: "Waaree Energies",
    companySector: "Renewable Energy",
    companyCategory: "Solar Manufacturing",
    companyStatus: "pre-ipo",
    quantity: 120,
    averageCost: 1420,
    indicativePrice: 1850,
    currentValue: 222000,
    investedValue: 170400,
    gain: 51600,
    gainPercent: 30.28,
    lastUpdated: "2026-08-19",
  },
]

// ─── Portfolio Summary ────────────────────────────────────────

export const portfolioSummary: Portfolio = {
  totalValue: 1785800,
  investedValue: 1357400,
  unrealisedGain: 428400,
  unrealisedGainPercent: 31.56,
  holdingsCount: 8,
  lastUpdated: "2026-08-19T02:15:00Z",
}

// ─── Portfolio Performance ────────────────────────────────────

function generatePerformance(months: number): PortfolioPerformancePoint[] {
  const now = new Date("2026-08-19")
  const base = 1000000
  const points: PortfolioPerformancePoint[] = []
  let value = base
  const totalDays = months * 30
  for (let i = totalDays; i >= 0; i -= Math.floor(totalDays / 60)) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    value = value * (1 + (Math.random() * 0.012 - 0.003))
    points.push({
      date: d.toISOString().split("T")[0],
      value: Math.round(value),
    })
  }
  // Ensure last point matches portfolio value
  points[points.length - 1].value = portfolioSummary.totalValue
  return points
}

export const portfolioPerformance = {
  "1M": generatePerformance(1),
  "3M": generatePerformance(3),
  "6M": generatePerformance(6),
  "1Y": generatePerformance(12),
  ALL: generatePerformance(24),
}

// ─── Allocation ───────────────────────────────────────────────

export const portfolioAllocation: AllocationItem[] = [
  { sector: "Financial Services", value: 609500, percent: 34.1, color: "#0EA5E9" },
  { sector: "Financial Infrastructure", value: 539800, percent: 30.2, color: "#071A2B" },
  { sector: "Technology", value: 226500, percent: 12.7, color: "#8b5cf6" },
  { sector: "Consumer Technology", value: 387500, percent: 21.7, color: "#D99A24" },
  { sector: "Renewable Energy", value: 222000, percent: 12.4, color: "#16A37A" },
]

// ─── Enquiries (in-memory, mutable) ───────────────────────────

export const enquiries: Enquiry[] = [
  {
    id: "enq-1",
    companyId: "tata-capital",
    companyName: "Tata Capital",
    type: "buy",
    quantity: 250,
    indicativePrice: 950,
    totalValue: 237500,
    status: "pending",
    notes: "Looking for long-term exposure to Tata Capital ahead of potential listing.",
    createdAt: "2026-08-15T10:30:00Z",
    updatedAt: "2026-08-15T10:30:00Z",
  },
  {
    id: "enq-2",
    companyId: "nse-india",
    companyName: "NSE India",
    type: "sell",
    quantity: 100,
    indicativePrice: 1998,
    totalValue: 199800,
    status: "under-review",
    notes: "Part exit to book partial gains.",
    createdAt: "2026-08-12T14:00:00Z",
    updatedAt: "2026-08-14T09:15:00Z",
  },
  {
    id: "enq-3",
    companyId: "waaree-energies",
    companyName: "Waaree Energies",
    type: "buy",
    quantity: 50,
    indicativePrice: 1850,
    totalValue: 92500,
    status: "completed",
    notes: "",
    createdAt: "2026-07-28T11:00:00Z",
    updatedAt: "2026-08-02T16:45:00Z",
  },
  {
    id: "enq-4",
    companyId: "oyo",
    companyName: "OYO Rooms",
    type: "sell",
    quantity: 1000,
    indicativePrice: 38,
    totalValue: 38000,
    status: "cancelled",
    notes: "Decided to hold and wait for potential recovery.",
    createdAt: "2026-07-20T09:00:00Z",
    updatedAt: "2026-07-21T10:30:00Z",
  },
]

// ─── Watchlist (in-memory, mutable) ───────────────────────────

export const watchlistItems: WatchlistItem[] = [
  {
    id: "wl-1",
    companyId: "hexaware",
    companyName: "Hexaware Technologies",
    sector: "Technology",
    category: "IT Services",
    status: "pre-ipo",
    indicativePrice: 755,
    previousPrice: 740,
    priceChange: 15,
    priceChangePercent: 2.03,
    lastUpdated: "2026-08-19",
    addedAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "wl-2",
    companyId: "swiggy",
    companyName: "Swiggy",
    sector: "Consumer Technology",
    category: "Food & Quick Commerce",
    status: "unlisted",
    indicativePrice: 395,
    previousPrice: 375,
    priceChange: 20,
    priceChangePercent: 5.33,
    lastUpdated: "2026-08-19",
    addedAt: "2026-07-25T12:00:00Z",
  },
]

// ─── KYC ─────────────────────────────────────────────────────

export const kycData: KYC = {
  overallStatus: "verified",
  lastUpdated: "2026-07-10T14:30:00Z",
  sections: [
    {
      id: "identity",
      label: "Identity Verification",
      status: "verified",
      completedAt: "2026-07-08T10:00:00Z",
      details: "Aadhaar-based e-KYC verified successfully.",
    },
    {
      id: "address",
      label: "Address Verification",
      status: "verified",
      completedAt: "2026-07-08T10:05:00Z",
      details: "Address verified via Aadhaar OTP.",
    },
    {
      id: "pan",
      label: "PAN Verification",
      status: "verified",
      completedAt: "2026-07-09T11:30:00Z",
      details: "PAN linked and NSDL verified.",
    },
    {
      id: "bank",
      label: "Bank Account Details",
      status: "verified",
      completedAt: "2026-07-10T09:00:00Z",
      details: "Bank account verified via penny drop.",
    },
    {
      id: "documents",
      label: "Supporting Documents",
      status: "verified",
      completedAt: "2026-07-10T14:30:00Z",
      details: "Signature and photograph uploaded and verified.",
    },
  ],
}

// ─── Profile ──────────────────────────────────────────────────

export let profileData: Profile = {
  id: "usr-001",
  name: "Arjun Sharma",
  email: "arjun.sharma@example.com",
  mobile: "+91 98765 43210",
  pan: "ABCPS1234Z",
  dob: "1990-04-15",
  address: "402, Serenity Towers, Bandra West",
  city: "Mumbai",
  state: "Maharashtra",
  pincode: "400050",
  avatarInitials: "AS",
  accountCreated: "2026-06-01T08:00:00Z",
  notifications: {
    email: true,
    sms: true,
    enquiryUpdates: true,
    priceAlerts: false,
    kycUpdates: true,
  },
}
